
export const ITEMS_PER_PAGE_OPTIONS_NUMBER_5 = 5;
export const ITEMS_PER_PAGE_OPTIONS_NUMBER_10 = 10;
export const ITEMS_PER_PAGE_OPTIONS_NUMBER_20 = 20;
export const ITEMS_PER_PAGE_OPTIONS_NUMBER_30 = 30;
export const ITEMS_PER_PAGE_OPTIONS_NUMBER_50 = 50;

export const SORT_DIRECTION_LABEL_OPTIONS_ASC = 'Ascending';
export const SORT_DIRECTION_LABEL_OPTIONS_DESC = 'Descending';

export const NUMBER_OPERATION_PAGINATOR = 1;