
export const environment = {
  production: false,
  stock_base_path: 'http://localhost:8081',
  user_base_path: 'http://localhost:8082',
  supply_base_path: 'http://localhost:8083',
  cart_base_path: 'http://localhost:8084',
  cart_controller: '/cart',
  supply_controller: '/api/v1/supplies',
  user_controller: '/api/v1/users',
  auth_controller: '/api/v1/auth',
  auth_post_login: '/login',
  user_post_customer: '/customer',
  user_post_warehouse: '/warehouse',
  category_controller: '/category',
  category_post_create: '/create',
  category_get_pagination: '/pagination/',
  category_get_all_categories: '/all',
  brand_controller: '/brand',
  brand_post_create: '/create',
  brand_get_pagination: '/pagination/',
  brand_get_all_brands: '/all',
  product_controller: '/product',
  product_post_create: '/',
  product_get_one_product: '/one',
  supply_post_add: '/',
  product_get_pagination: '/pagination/',
  cart_post_add: '/add',
  cart_post_remove_product_to_cart: '/remove',
  cart_get_pagination_cart: '/pagination/',
  cart_get_list_cart_details: '/cart/details/',
  auth_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlBvd2VyIFVwIEZ1bGwgU3RhY2siLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNTE2MjM5MDIyfQ.8r-71aFvp9lUbJHbUQnkHTYzlfZsdeF5n2ZZedqgee4"
};

